Add Service Binding Support
cloudflare/workers-rs pull request #183
Opened 2022-05-14 13:23 UTC by ImSingee

The PR adds support for [Service Bindings](https://developers.cloudflare.com/workers/platform/bindings/about-service-bindings/)

2022-05-16 14:55 UTC, zebp requested changes
Looks good but needs some minor tweaks. I think we need to use the name `Service` instead of `Remote service` and we need to add testing in `worker-sandbox/`.

Service bindings in Miniflare seem a little rough right now, it seems that we'll need to update the GH action to add a service binding test.

2022-05-16 14:55 UTC, zebp commented on worker-sys/src/remote_service.rs
> +    pub type RemoteService;
We should try to either match the [workers-types](https://github.com/cloudflare/workers-types) name `Fetcher` or just use `Service`. I think we should replace all occurences of `RemoteService` with `Service`.

2022-05-16 14:55 UTC, zebp commented on worker/src/env.rs
> +    pub fn remote_service(&self, binding: &str) -> Result<RemoteService> {
Should be named `service`

2022-05-18 00:14 UTC, ImSingee commented
@zebp For the name, I think now (in the dashboard) the previous `Worker Script` is now totally renamed to `Service`, So I think a `Service Binding` implies the `Remote Service Binding`, which is difference from the current local binding.

I don't think my name is right, but I don't think just name it`service` is good either.

2022-05-18 00:22 UTC, ImSingee commented
For test, I think we must use [wrangler2](https://github.com/cloudflare/wrangler2), and it seems that the `wrangler.toml` should be changed too, maybe like this (remove `type` and change `build.upload` to `main`):

```
name = "testing-rust-worker"
workers_dev = true
compatibility_date = "2021-11-27" # required
main = "build/worker/shim.js"

kv_namespaces = [
    { binding = "SOME_NAMESPACE", id = "", preview_id = "" },
    { binding = "FILE_SIZES", id = "", preview_id = "" },
]

vars = { SOME_VARIABLE = "some value" }

[durable_objects]
bindings = [{ name = "COUNTER", class_name = "Counter" }]

[build]
command = "worker-build --release"

```

And after the migration to wrangler2 is done, I think I can add a test easily.

BTW, the current support for service binding in wrangler2 is merged (in https://github.com/cloudflare/wrangler2/pull/906) but isn't release now, so maybe we need to wait their release?

2022-07-27 15:03 UTC, cjpatton commented
miniflare 2.6.0 allegedly has bineings support: https://github.com/cloudflare/miniflare/issues/301

2022-10-14 18:12 UTC, sergey-melnychuk commented
Friendly ping @zebp @ImSingee 
Any chance making some progress here anytime soon?
If not, any objections if I pick it put and push to an acceptable form?

2022-11-17 15:23 UTC, zebp commented
Closing in favor of #243

2022-11-17 15:23 UTC, closed without merging