Add DO Alarm API
cloudflare/workers-rs pull request #189
Opened 2022-05-18 22:43 UTC by fisherdarling

This PR implements the DO Alarm API based off of the signatures found in the [storage docs](https://developers.cloudflare.com/workers/runtime-apis/durable-objects/#methods).

I think there's a bug in the way I've implemented the binding for `getAlarm`. When an alarm does not exist, I expect `getAlarm` to return `null` and in rust `Ok(None)`, however I seem to be getting an error instead. When the alarm does exist (`set_alarm` immediately followed by a `get_alarm`) I get the expected output.

I haven't been able to test that the alarm does trigger, however everything compiles and it looks like the generated shim has the required methods. I'll be testing later tonight.

2022-06-06 13:54 UTC, zebp requested changes
Some changes needed, but overall looks good. The new methods need to have option arguments and we need to add testing for this in `worker-sandbox`. Miniflare support for DO alarms seems a bit rough right now, but should be good enough for us to get basic testing.

Sorry for the delay on the review.

2022-06-06 13:54 UTC, zebp commented on worker/src/durable.rs
> +    pub async fn set_alarm(&self, scheduled_time: DateTime<Utc>) -> Result<()> {
Should have an optional options parameter that matches [setAlarm](https://github.com/cloudflare/workers-types/blob/master/index.d.ts#L434) from the workers-types repo.

As for the time parameter, maybe we could have an enum that's either a datetime or a delay and then update the method to be:
```rust
impl From<i64> for ScheduledTime { /* snip */ }
impl From<DateTime<Utc>> for ScheduledTime { /* snip */ }

pub async fn set_alarm(
    &self, 
    scheduled_time: impl Into<ScheduledTime>,
    options: Option<SetAlarmOptions>,
) -> Result<()> {
    // code
}
```

2022-06-06 13:54 UTC, zebp commented on worker/src/durable.rs
> +    pub async fn get_alarm(&self) -> Result<Option<i64>> {
Should have an optional options parameter that matches [getAlarm](https://github.com/cloudflare/workers-types/blob/master/index.d.ts#L433) from the workers-types repo.

2022-06-06 13:54 UTC, zebp commented on worker/src/durable.rs
> +    pub async fn get_alarm(&self) -> Result<Option<i64>> {
Should have an optional options parameter that matches [getAlarm](https://github.com/cloudflare/workers-types/blob/master/index.d.ts#L433) from the workers-types repo.

2022-06-06 13:54 UTC, zebp commented on worker/src/durable.rs
> +    pub async fn delete_alarm(&self) -> Result<()> {
Should have an optional options parameter that matches [deleteAlarm](https://github.com/cloudflare/workers-types/blob/master/index.d.ts#L438) from the workers-types repo.

2022-06-06 13:54 UTC, zebp commented on worker/src/durable.rs
> +    pub async fn delete_alarm(&self) -> Result<()> {
Should have an optional options parameter that matches [deleteAlarm](https://github.com/cloudflare/workers-types/blob/master/index.d.ts#L438) from the workers-types repo.

2022-06-06 14:36 UTC, fisherdarling commented
> Some changes needed, but overall looks good. The new methods need to have option arguments and we need to add testing for this in `worker-sandbox`. Miniflare support for DO alarms seems a bit rough right now, but should be good enough for us to get basic testing.
> 
> 
> 
> Sorry for the delay on the review.

@zebp Sounds good! I like the idea of using a trait for the argument. No worries on the delayed review too.

I'll also add some tests and those optional arguments as well.

I have some family visiting me right now so aim to get the additional work done sometime next Monday or Tuesday.

2022-06-12 11:11 UTC, fisherdarling commented
@zebp Currently stuck on testing. A few days ago I tried to add some and I didn't get it to really work locally.

2022-08-11 20:53 UTC, zebp requested changes
Hey sorry about this review not happening sooner, but better late than never I guess! Some minor changes but this looks pretty good, we also probably should rebase this on `main`.

We'll probably finish this up ourselves as it's a blocker for us.

2022-08-11 20:53 UTC, zebp commented on worker/src/durable.rs
> +pub struct ScheduledTime {
Nitpick but this struct should probably impl `From<Duration>`. And a small explanation for why this exists in some documentation would probably be useful as it isn't exactly clear from the usage in `set_alarm`.

2022-08-11 20:53 UTC, zebp commented on worker-sandbox/src/counter.rs
> +    async fn alarm(&mut self) -> Result<Response> {
We should move the alarm logic to a different durable object and then run tests on that, but something like this is what I would do. We'd also need to update the test in `worker-sandbox/tests/requests.rs`.

2022-08-11 20:53 UTC, zebp commented on worker-sandbox/wrangler.toml
> +    { binding = "SOME_NAMESPACE", id = "A", preview_id = "B" },
These should get changed back.

2022-08-11 20:53 UTC, zebp commented on worker/src/durable.rs
> +pub struct GetAlarmOptions {
These structs their fields marked as `pub` so they be set by anyone and the structs should also derive `Debug` and `Clone`.

2022-08-18 18:45 UTC, zebp approved these changes

2022-08-18 18:46 UTC, zebp commented
Finished up and rebased this PR, thanks for the contribution!

2022-08-18 18:46 UTC, merged