Add Service Bindings support
cloudflare/workers-rs pull request #235
Opened 2022-10-14 21:09 UTC by sergey-melnychuk

CloudFlare Workers Service Bindings:
https://developers.cloudflare.com/workers/platform/bindings/about-service-bindings/

Inspiration:
https://github.com/cloudflare/workers-rs/pull/183

This implementation was verified to work against live CloudFlare services.

2022-10-14 21:09 UTC, sergey-melnychuk commented
@zebp PTAL

2022-11-16 21:50 UTC, zebp requested changes
Thanks for the contribution, looks solid for the most part. A couple things like reusing existing dynamic dispatch binding logic and adding testing is needed so I'll be taking this PR over and finishing this up as this has become a priority.

2022-11-16 21:50 UTC, zebp commented on worker-sys/src/service.rs
> +    pub type Service;
Now that dynamic dispatch is added, some of this boilerplate can be merged with [`Fetcher`](https://github.com/cloudflare/workers-rs/blob/main/worker-sys/src/fetcher.rs#L9).

2022-11-16 21:50 UTC, zebp commented on worker/src/service.rs
> +pub struct Service {
Same with this, should be able to merge this with the existing [`Fetcher`](https://github.com/cloudflare/workers-rs/blob/main/worker/src/fetcher.rs#L8).

2022-11-17 15:23 UTC, zebp commented
Closing in favor of #243

2022-11-17 15:23 UTC, closed without merging