add get_field helper method
cloudflare/workers-rs pull request #398
Opened 2023-09-27 18:41 UTC by dev-ardi

This PR creates a helper method for `FormData` so that users don't have to pattern match for `FormEntry::Field` every time they want to use this. 99% of the time the passed arguments aren't files.

2023-09-30 20:52 UTC, zebp requested changes
LGTM but the formatting needs to be fixed.

2023-09-30 22:36 UTC, dev-ardi commented
> LGTM but the formatting needs to be fixed.

Whoops, done :)

2023-10-02 19:13 UTC, dev-ardi commented
@zebp CI is failing after running `cargo fmt`, what's up with that?

2023-10-02 19:16 UTC, zebp commented
> @zebp CI is failing after running `cargo fmt`, what's up with that?

CI is currently not passing on the revision of main your PR is based because of a new clippy lint, I updated main yesterdahy so you should be fine if you rebase the PR.

2023-11-08 15:23 UTC, kflansburg approved these changes

2023-11-08 15:23 UTC, merged