Add a binding to meta object for `D1Result`.
cloudflare/workers-rs pull request #591
Opened 2024-07-04 20:37 UTC by langyo

Thanks to the official staff for reviewing. This PR is based on #337 .

When I tried to use `sea-orm` proxy connection, I found that the `D1Result` object could not obtain other information except data, so I traced the source code.

In fact, `worker-sys` has already declared the `meta` function, but `D1Result` under `worker` did not further extract and serialize this part of data. I made some simple work that `D1Result` can obtain this part of the content.

[Demo is here](https://github.com/langyo/cloudflare_worker_rust_demo).

2024-07-04 20:41 UTC, kflansburg requested changes

2024-07-04 20:41 UTC, kflansburg commented on worker/src/d1/mod.rs
> +    /// Returns `None` if it's not exists.
I'm actually not sure when this would not be included in the result.
```suggestion
    /// Returns `None` if `meta` field is not populated.
```

2024-07-04 20:41 UTC, kflansburg commented on worker/src/d1/mod.rs
> +            let meta: D1ResultMeta = serde_wasm_bindgen::from_value(meta.into()).unwrap();
Could you remove this unwrap?

2024-07-04 20:43 UTC, langyo commented on worker/src/d1/mod.rs
> +            let meta: D1ResultMeta = serde_wasm_bindgen::from_value(meta.into()).unwrap();
> Could you remove this unwrap?

Okay, I neglected it.

2024-07-05 15:35 UTC, kflansburg approved these changes

2024-07-05 15:39 UTC, merged